// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/gateway.proto

#include "proto/gateway.pb.h"
#include "proto/gateway.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace gateway {

static const char* GatewayService_method_names[] = {
  "/gateway.GatewayService/ForwardMessage",
  "/gateway.GatewayService/ForwardMessageBatch",
  "/gateway.GatewayService/HealthCheck",
  "/gateway.GatewayService/GetNodeStats",
};

std::unique_ptr< GatewayService::Stub> GatewayService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GatewayService::Stub> stub(new GatewayService::Stub(channel, options));
  return stub;
}

GatewayService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ForwardMessage_(GatewayService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ForwardMessageBatch_(GatewayService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HealthCheck_(GatewayService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNodeStats_(GatewayService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GatewayService::Stub::ForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::gateway::ForwardMessageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gateway::ForwardMessageRequest, ::gateway::ForwardMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ForwardMessage_, context, request, response);
}

void GatewayService::Stub::async::ForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest* request, ::gateway::ForwardMessageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gateway::ForwardMessageRequest, ::gateway::ForwardMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ForwardMessage_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::ForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest* request, ::gateway::ForwardMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ForwardMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageResponse>* GatewayService::Stub::PrepareAsyncForwardMessageRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gateway::ForwardMessageResponse, ::gateway::ForwardMessageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ForwardMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageResponse>* GatewayService::Stub::AsyncForwardMessageRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncForwardMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GatewayService::Stub::ForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::gateway::ForwardMessageBatchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gateway::ForwardMessageBatchRequest, ::gateway::ForwardMessageBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ForwardMessageBatch_, context, request, response);
}

void GatewayService::Stub::async::ForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest* request, ::gateway::ForwardMessageBatchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gateway::ForwardMessageBatchRequest, ::gateway::ForwardMessageBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ForwardMessageBatch_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::ForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest* request, ::gateway::ForwardMessageBatchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ForwardMessageBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageBatchResponse>* GatewayService::Stub::PrepareAsyncForwardMessageBatchRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gateway::ForwardMessageBatchResponse, ::gateway::ForwardMessageBatchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ForwardMessageBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageBatchResponse>* GatewayService::Stub::AsyncForwardMessageBatchRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncForwardMessageBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GatewayService::Stub::HealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::gateway::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gateway::HealthCheckRequest, ::gateway::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void GatewayService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest* request, ::gateway::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gateway::HealthCheckRequest, ::gateway::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest* request, ::gateway::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gateway::HealthCheckResponse>* GatewayService::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gateway::HealthCheckResponse, ::gateway::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gateway::HealthCheckResponse>* GatewayService::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GatewayService::Stub::GetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::gateway::NodeStatsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gateway::NodeStatsRequest, ::gateway::NodeStatsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNodeStats_, context, request, response);
}

void GatewayService::Stub::async::GetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest* request, ::gateway::NodeStatsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gateway::NodeStatsRequest, ::gateway::NodeStatsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeStats_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::GetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest* request, ::gateway::NodeStatsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gateway::NodeStatsResponse>* GatewayService::Stub::PrepareAsyncGetNodeStatsRaw(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gateway::NodeStatsResponse, ::gateway::NodeStatsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNodeStats_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gateway::NodeStatsResponse>* GatewayService::Stub::AsyncGetNodeStatsRaw(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodeStatsRaw(context, request, cq);
  result->StartCall();
  return result;
}

GatewayService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::gateway::ForwardMessageRequest, ::gateway::ForwardMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gateway::ForwardMessageRequest* req,
             ::gateway::ForwardMessageResponse* resp) {
               return service->ForwardMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::gateway::ForwardMessageBatchRequest, ::gateway::ForwardMessageBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gateway::ForwardMessageBatchRequest* req,
             ::gateway::ForwardMessageBatchResponse* resp) {
               return service->ForwardMessageBatch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::gateway::HealthCheckRequest, ::gateway::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gateway::HealthCheckRequest* req,
             ::gateway::HealthCheckResponse* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::gateway::NodeStatsRequest, ::gateway::NodeStatsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gateway::NodeStatsRequest* req,
             ::gateway::NodeStatsResponse* resp) {
               return service->GetNodeStats(ctx, req, resp);
             }, this)));
}

GatewayService::Service::~Service() {
}

::grpc::Status GatewayService::Service::ForwardMessage(::grpc::ServerContext* context, const ::gateway::ForwardMessageRequest* request, ::gateway::ForwardMessageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::ForwardMessageBatch(::grpc::ServerContext* context, const ::gateway::ForwardMessageBatchRequest* request, ::gateway::ForwardMessageBatchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::HealthCheck(::grpc::ServerContext* context, const ::gateway::HealthCheckRequest* request, ::gateway::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::GetNodeStats(::grpc::ServerContext* context, const ::gateway::NodeStatsRequest* request, ::gateway::NodeStatsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gateway

