// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fgateway_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fgateway_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fgateway_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fgateway_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fgateway_2eproto;
namespace gateway {
class ForwardMessageBatchRequest;
struct ForwardMessageBatchRequestDefaultTypeInternal;
extern ForwardMessageBatchRequestDefaultTypeInternal _ForwardMessageBatchRequest_default_instance_;
class ForwardMessageBatchResponse;
struct ForwardMessageBatchResponseDefaultTypeInternal;
extern ForwardMessageBatchResponseDefaultTypeInternal _ForwardMessageBatchResponse_default_instance_;
class ForwardMessageRequest;
struct ForwardMessageRequestDefaultTypeInternal;
extern ForwardMessageRequestDefaultTypeInternal _ForwardMessageRequest_default_instance_;
class ForwardMessageResponse;
struct ForwardMessageResponseDefaultTypeInternal;
extern ForwardMessageResponseDefaultTypeInternal _ForwardMessageResponse_default_instance_;
class HealthCheckRequest;
struct HealthCheckRequestDefaultTypeInternal;
extern HealthCheckRequestDefaultTypeInternal _HealthCheckRequest_default_instance_;
class HealthCheckResponse;
struct HealthCheckResponseDefaultTypeInternal;
extern HealthCheckResponseDefaultTypeInternal _HealthCheckResponse_default_instance_;
class NodeStatsRequest;
struct NodeStatsRequestDefaultTypeInternal;
extern NodeStatsRequestDefaultTypeInternal _NodeStatsRequest_default_instance_;
class NodeStatsResponse;
struct NodeStatsResponseDefaultTypeInternal;
extern NodeStatsResponseDefaultTypeInternal _NodeStatsResponse_default_instance_;
}  // namespace gateway
PROTOBUF_NAMESPACE_OPEN
template<> ::gateway::ForwardMessageBatchRequest* Arena::CreateMaybeMessage<::gateway::ForwardMessageBatchRequest>(Arena*);
template<> ::gateway::ForwardMessageBatchResponse* Arena::CreateMaybeMessage<::gateway::ForwardMessageBatchResponse>(Arena*);
template<> ::gateway::ForwardMessageRequest* Arena::CreateMaybeMessage<::gateway::ForwardMessageRequest>(Arena*);
template<> ::gateway::ForwardMessageResponse* Arena::CreateMaybeMessage<::gateway::ForwardMessageResponse>(Arena*);
template<> ::gateway::HealthCheckRequest* Arena::CreateMaybeMessage<::gateway::HealthCheckRequest>(Arena*);
template<> ::gateway::HealthCheckResponse* Arena::CreateMaybeMessage<::gateway::HealthCheckResponse>(Arena*);
template<> ::gateway::NodeStatsRequest* Arena::CreateMaybeMessage<::gateway::NodeStatsRequest>(Arena*);
template<> ::gateway::NodeStatsResponse* Arena::CreateMaybeMessage<::gateway::NodeStatsResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gateway {

// ===================================================================

class ForwardMessageRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.ForwardMessageRequest) */ {
 public:
  inline ForwardMessageRequest() : ForwardMessageRequest(nullptr) {}
  ~ForwardMessageRequest() override;
  explicit PROTOBUF_CONSTEXPR ForwardMessageRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ForwardMessageRequest(const ForwardMessageRequest& from);
  ForwardMessageRequest(ForwardMessageRequest&& from) noexcept
    : ForwardMessageRequest() {
    *this = ::std::move(from);
  }

  inline ForwardMessageRequest& operator=(const ForwardMessageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForwardMessageRequest& operator=(ForwardMessageRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ForwardMessageRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ForwardMessageRequest* internal_default_instance() {
    return reinterpret_cast<const ForwardMessageRequest*>(
               &_ForwardMessageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ForwardMessageRequest& a, ForwardMessageRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ForwardMessageRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForwardMessageRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ForwardMessageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ForwardMessageRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ForwardMessageRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ForwardMessageRequest& from) {
    ForwardMessageRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ForwardMessageRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.ForwardMessageRequest";
  }
  protected:
  explicit ForwardMessageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 1,
    kMessageFieldNumber = 2,
    kFromNodeFieldNumber = 3,
    kTimestampFieldNumber = 4,
  };
  // string user_id = 1;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // string from_node = 3;
  void clear_from_node();
  const std::string& from_node() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_from_node(ArgT0&& arg0, ArgT... args);
  std::string* mutable_from_node();
  PROTOBUF_NODISCARD std::string* release_from_node();
  void set_allocated_from_node(std::string* from_node);
  private:
  const std::string& _internal_from_node() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_from_node(const std::string& value);
  std::string* _internal_mutable_from_node();
  public:

  // int64 timestamp = 4;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:gateway.ForwardMessageRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr from_node_;
    int64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fgateway_2eproto;
};
// -------------------------------------------------------------------

class ForwardMessageResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.ForwardMessageResponse) */ {
 public:
  inline ForwardMessageResponse() : ForwardMessageResponse(nullptr) {}
  ~ForwardMessageResponse() override;
  explicit PROTOBUF_CONSTEXPR ForwardMessageResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ForwardMessageResponse(const ForwardMessageResponse& from);
  ForwardMessageResponse(ForwardMessageResponse&& from) noexcept
    : ForwardMessageResponse() {
    *this = ::std::move(from);
  }

  inline ForwardMessageResponse& operator=(const ForwardMessageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForwardMessageResponse& operator=(ForwardMessageResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ForwardMessageResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ForwardMessageResponse* internal_default_instance() {
    return reinterpret_cast<const ForwardMessageResponse*>(
               &_ForwardMessageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ForwardMessageResponse& a, ForwardMessageResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ForwardMessageResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForwardMessageResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ForwardMessageResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ForwardMessageResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ForwardMessageResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ForwardMessageResponse& from) {
    ForwardMessageResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ForwardMessageResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.ForwardMessageResponse";
  }
  protected:
  explicit ForwardMessageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
    kUserOnlineFieldNumber = 3,
  };
  // string error_message = 2;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // bool user_online = 3;
  void clear_user_online();
  bool user_online() const;
  void set_user_online(bool value);
  private:
  bool _internal_user_online() const;
  void _internal_set_user_online(bool value);
  public:

  // @@protoc_insertion_point(class_scope:gateway.ForwardMessageResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    bool success_;
    bool user_online_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fgateway_2eproto;
};
// -------------------------------------------------------------------

class ForwardMessageBatchRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.ForwardMessageBatchRequest) */ {
 public:
  inline ForwardMessageBatchRequest() : ForwardMessageBatchRequest(nullptr) {}
  ~ForwardMessageBatchRequest() override;
  explicit PROTOBUF_CONSTEXPR ForwardMessageBatchRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ForwardMessageBatchRequest(const ForwardMessageBatchRequest& from);
  ForwardMessageBatchRequest(ForwardMessageBatchRequest&& from) noexcept
    : ForwardMessageBatchRequest() {
    *this = ::std::move(from);
  }

  inline ForwardMessageBatchRequest& operator=(const ForwardMessageBatchRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForwardMessageBatchRequest& operator=(ForwardMessageBatchRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ForwardMessageBatchRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ForwardMessageBatchRequest* internal_default_instance() {
    return reinterpret_cast<const ForwardMessageBatchRequest*>(
               &_ForwardMessageBatchRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ForwardMessageBatchRequest& a, ForwardMessageBatchRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ForwardMessageBatchRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForwardMessageBatchRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ForwardMessageBatchRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ForwardMessageBatchRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ForwardMessageBatchRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ForwardMessageBatchRequest& from) {
    ForwardMessageBatchRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ForwardMessageBatchRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.ForwardMessageBatchRequest";
  }
  protected:
  explicit ForwardMessageBatchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessagesFieldNumber = 1,
  };
  // repeated .gateway.ForwardMessageRequest messages = 1;
  int messages_size() const;
  private:
  int _internal_messages_size() const;
  public:
  void clear_messages();
  ::gateway::ForwardMessageRequest* mutable_messages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::ForwardMessageRequest >*
      mutable_messages();
  private:
  const ::gateway::ForwardMessageRequest& _internal_messages(int index) const;
  ::gateway::ForwardMessageRequest* _internal_add_messages();
  public:
  const ::gateway::ForwardMessageRequest& messages(int index) const;
  ::gateway::ForwardMessageRequest* add_messages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::ForwardMessageRequest >&
      messages() const;

  // @@protoc_insertion_point(class_scope:gateway.ForwardMessageBatchRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::ForwardMessageRequest > messages_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fgateway_2eproto;
};
// -------------------------------------------------------------------

class ForwardMessageBatchResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.ForwardMessageBatchResponse) */ {
 public:
  inline ForwardMessageBatchResponse() : ForwardMessageBatchResponse(nullptr) {}
  ~ForwardMessageBatchResponse() override;
  explicit PROTOBUF_CONSTEXPR ForwardMessageBatchResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ForwardMessageBatchResponse(const ForwardMessageBatchResponse& from);
  ForwardMessageBatchResponse(ForwardMessageBatchResponse&& from) noexcept
    : ForwardMessageBatchResponse() {
    *this = ::std::move(from);
  }

  inline ForwardMessageBatchResponse& operator=(const ForwardMessageBatchResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForwardMessageBatchResponse& operator=(ForwardMessageBatchResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ForwardMessageBatchResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ForwardMessageBatchResponse* internal_default_instance() {
    return reinterpret_cast<const ForwardMessageBatchResponse*>(
               &_ForwardMessageBatchResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ForwardMessageBatchResponse& a, ForwardMessageBatchResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ForwardMessageBatchResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForwardMessageBatchResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ForwardMessageBatchResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ForwardMessageBatchResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ForwardMessageBatchResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ForwardMessageBatchResponse& from) {
    ForwardMessageBatchResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ForwardMessageBatchResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.ForwardMessageBatchResponse";
  }
  protected:
  explicit ForwardMessageBatchResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorsFieldNumber = 3,
    kSuccessCountFieldNumber = 1,
    kFailedCountFieldNumber = 2,
  };
  // repeated string errors = 3;
  int errors_size() const;
  private:
  int _internal_errors_size() const;
  public:
  void clear_errors();
  const std::string& errors(int index) const;
  std::string* mutable_errors(int index);
  void set_errors(int index, const std::string& value);
  void set_errors(int index, std::string&& value);
  void set_errors(int index, const char* value);
  void set_errors(int index, const char* value, size_t size);
  std::string* add_errors();
  void add_errors(const std::string& value);
  void add_errors(std::string&& value);
  void add_errors(const char* value);
  void add_errors(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& errors() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_errors();
  private:
  const std::string& _internal_errors(int index) const;
  std::string* _internal_add_errors();
  public:

  // int32 success_count = 1;
  void clear_success_count();
  int32_t success_count() const;
  void set_success_count(int32_t value);
  private:
  int32_t _internal_success_count() const;
  void _internal_set_success_count(int32_t value);
  public:

  // int32 failed_count = 2;
  void clear_failed_count();
  int32_t failed_count() const;
  void set_failed_count(int32_t value);
  private:
  int32_t _internal_failed_count() const;
  void _internal_set_failed_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:gateway.ForwardMessageBatchResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> errors_;
    int32_t success_count_;
    int32_t failed_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fgateway_2eproto;
};
// -------------------------------------------------------------------

class HealthCheckRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.HealthCheckRequest) */ {
 public:
  inline HealthCheckRequest() : HealthCheckRequest(nullptr) {}
  ~HealthCheckRequest() override;
  explicit PROTOBUF_CONSTEXPR HealthCheckRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HealthCheckRequest(const HealthCheckRequest& from);
  HealthCheckRequest(HealthCheckRequest&& from) noexcept
    : HealthCheckRequest() {
    *this = ::std::move(from);
  }

  inline HealthCheckRequest& operator=(const HealthCheckRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HealthCheckRequest& operator=(HealthCheckRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HealthCheckRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HealthCheckRequest* internal_default_instance() {
    return reinterpret_cast<const HealthCheckRequest*>(
               &_HealthCheckRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(HealthCheckRequest& a, HealthCheckRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HealthCheckRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HealthCheckRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HealthCheckRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HealthCheckRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HealthCheckRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HealthCheckRequest& from) {
    HealthCheckRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HealthCheckRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.HealthCheckRequest";
  }
  protected:
  explicit HealthCheckRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
  };
  // string node_id = 1;
  void clear_node_id();
  const std::string& node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // @@protoc_insertion_point(class_scope:gateway.HealthCheckRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fgateway_2eproto;
};
// -------------------------------------------------------------------

class HealthCheckResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.HealthCheckResponse) */ {
 public:
  inline HealthCheckResponse() : HealthCheckResponse(nullptr) {}
  ~HealthCheckResponse() override;
  explicit PROTOBUF_CONSTEXPR HealthCheckResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HealthCheckResponse(const HealthCheckResponse& from);
  HealthCheckResponse(HealthCheckResponse&& from) noexcept
    : HealthCheckResponse() {
    *this = ::std::move(from);
  }

  inline HealthCheckResponse& operator=(const HealthCheckResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline HealthCheckResponse& operator=(HealthCheckResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HealthCheckResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const HealthCheckResponse* internal_default_instance() {
    return reinterpret_cast<const HealthCheckResponse*>(
               &_HealthCheckResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(HealthCheckResponse& a, HealthCheckResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(HealthCheckResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HealthCheckResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HealthCheckResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HealthCheckResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HealthCheckResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HealthCheckResponse& from) {
    HealthCheckResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HealthCheckResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.HealthCheckResponse";
  }
  protected:
  explicit HealthCheckResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHealthyFieldNumber = 1,
    kActiveConnectionsFieldNumber = 2,
    kCpuUsageFieldNumber = 4,
    kMemoryUsageFieldNumber = 5,
    kTotalConnectionsFieldNumber = 3,
  };
  // bool healthy = 1;
  void clear_healthy();
  bool healthy() const;
  void set_healthy(bool value);
  private:
  bool _internal_healthy() const;
  void _internal_set_healthy(bool value);
  public:

  // int32 active_connections = 2;
  void clear_active_connections();
  int32_t active_connections() const;
  void set_active_connections(int32_t value);
  private:
  int32_t _internal_active_connections() const;
  void _internal_set_active_connections(int32_t value);
  public:

  // double cpu_usage = 4;
  void clear_cpu_usage();
  double cpu_usage() const;
  void set_cpu_usage(double value);
  private:
  double _internal_cpu_usage() const;
  void _internal_set_cpu_usage(double value);
  public:

  // double memory_usage = 5;
  void clear_memory_usage();
  double memory_usage() const;
  void set_memory_usage(double value);
  private:
  double _internal_memory_usage() const;
  void _internal_set_memory_usage(double value);
  public:

  // int32 total_connections = 3;
  void clear_total_connections();
  int32_t total_connections() const;
  void set_total_connections(int32_t value);
  private:
  int32_t _internal_total_connections() const;
  void _internal_set_total_connections(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:gateway.HealthCheckResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool healthy_;
    int32_t active_connections_;
    double cpu_usage_;
    double memory_usage_;
    int32_t total_connections_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fgateway_2eproto;
};
// -------------------------------------------------------------------

class NodeStatsRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.NodeStatsRequest) */ {
 public:
  inline NodeStatsRequest() : NodeStatsRequest(nullptr) {}
  ~NodeStatsRequest() override;
  explicit PROTOBUF_CONSTEXPR NodeStatsRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NodeStatsRequest(const NodeStatsRequest& from);
  NodeStatsRequest(NodeStatsRequest&& from) noexcept
    : NodeStatsRequest() {
    *this = ::std::move(from);
  }

  inline NodeStatsRequest& operator=(const NodeStatsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeStatsRequest& operator=(NodeStatsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NodeStatsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const NodeStatsRequest* internal_default_instance() {
    return reinterpret_cast<const NodeStatsRequest*>(
               &_NodeStatsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(NodeStatsRequest& a, NodeStatsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(NodeStatsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeStatsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NodeStatsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NodeStatsRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NodeStatsRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NodeStatsRequest& from) {
    NodeStatsRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeStatsRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.NodeStatsRequest";
  }
  protected:
  explicit NodeStatsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
  };
  // string node_id = 1;
  void clear_node_id();
  const std::string& node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // @@protoc_insertion_point(class_scope:gateway.NodeStatsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fgateway_2eproto;
};
// -------------------------------------------------------------------

class NodeStatsResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gateway.NodeStatsResponse) */ {
 public:
  inline NodeStatsResponse() : NodeStatsResponse(nullptr) {}
  ~NodeStatsResponse() override;
  explicit PROTOBUF_CONSTEXPR NodeStatsResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NodeStatsResponse(const NodeStatsResponse& from);
  NodeStatsResponse(NodeStatsResponse&& from) noexcept
    : NodeStatsResponse() {
    *this = ::std::move(from);
  }

  inline NodeStatsResponse& operator=(const NodeStatsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeStatsResponse& operator=(NodeStatsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NodeStatsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const NodeStatsResponse* internal_default_instance() {
    return reinterpret_cast<const NodeStatsResponse*>(
               &_NodeStatsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(NodeStatsResponse& a, NodeStatsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(NodeStatsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeStatsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NodeStatsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NodeStatsResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NodeStatsResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NodeStatsResponse& from) {
    NodeStatsResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeStatsResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gateway.NodeStatsResponse";
  }
  protected:
  explicit NodeStatsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
    kActiveConnectionsFieldNumber = 2,
    kTotalConnectionsFieldNumber = 3,
    kMessagesReceivedFieldNumber = 4,
    kMessagesSentFieldNumber = 5,
    kUptimeSecondsFieldNumber = 6,
  };
  // string node_id = 1;
  void clear_node_id();
  const std::string& node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // int32 active_connections = 2;
  void clear_active_connections();
  int32_t active_connections() const;
  void set_active_connections(int32_t value);
  private:
  int32_t _internal_active_connections() const;
  void _internal_set_active_connections(int32_t value);
  public:

  // int32 total_connections = 3;
  void clear_total_connections();
  int32_t total_connections() const;
  void set_total_connections(int32_t value);
  private:
  int32_t _internal_total_connections() const;
  void _internal_set_total_connections(int32_t value);
  public:

  // int64 messages_received = 4;
  void clear_messages_received();
  int64_t messages_received() const;
  void set_messages_received(int64_t value);
  private:
  int64_t _internal_messages_received() const;
  void _internal_set_messages_received(int64_t value);
  public:

  // int64 messages_sent = 5;
  void clear_messages_sent();
  int64_t messages_sent() const;
  void set_messages_sent(int64_t value);
  private:
  int64_t _internal_messages_sent() const;
  void _internal_set_messages_sent(int64_t value);
  public:

  // int64 uptime_seconds = 6;
  void clear_uptime_seconds();
  int64_t uptime_seconds() const;
  void set_uptime_seconds(int64_t value);
  private:
  int64_t _internal_uptime_seconds() const;
  void _internal_set_uptime_seconds(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:gateway.NodeStatsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
    int32_t active_connections_;
    int32_t total_connections_;
    int64_t messages_received_;
    int64_t messages_sent_;
    int64_t uptime_seconds_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fgateway_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ForwardMessageRequest

// string user_id = 1;
inline void ForwardMessageRequest::clear_user_id() {
  _impl_.user_id_.ClearToEmpty();
}
inline const std::string& ForwardMessageRequest::user_id() const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageRequest.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ForwardMessageRequest::set_user_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageRequest.user_id)
}
inline std::string* ForwardMessageRequest::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:gateway.ForwardMessageRequest.user_id)
  return _s;
}
inline const std::string& ForwardMessageRequest::_internal_user_id() const {
  return _impl_.user_id_.Get();
}
inline void ForwardMessageRequest::_internal_set_user_id(const std::string& value) {
  
  _impl_.user_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ForwardMessageRequest::_internal_mutable_user_id() {
  
  return _impl_.user_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ForwardMessageRequest::release_user_id() {
  // @@protoc_insertion_point(field_release:gateway.ForwardMessageRequest.user_id)
  return _impl_.user_id_.Release();
}
inline void ForwardMessageRequest::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    
  } else {
    
  }
  _impl_.user_id_.SetAllocated(user_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gateway.ForwardMessageRequest.user_id)
}

// string message = 2;
inline void ForwardMessageRequest::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ForwardMessageRequest::message() const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageRequest.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ForwardMessageRequest::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageRequest.message)
}
inline std::string* ForwardMessageRequest::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:gateway.ForwardMessageRequest.message)
  return _s;
}
inline const std::string& ForwardMessageRequest::_internal_message() const {
  return _impl_.message_.Get();
}
inline void ForwardMessageRequest::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* ForwardMessageRequest::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* ForwardMessageRequest::release_message() {
  // @@protoc_insertion_point(field_release:gateway.ForwardMessageRequest.message)
  return _impl_.message_.Release();
}
inline void ForwardMessageRequest::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gateway.ForwardMessageRequest.message)
}

// string from_node = 3;
inline void ForwardMessageRequest::clear_from_node() {
  _impl_.from_node_.ClearToEmpty();
}
inline const std::string& ForwardMessageRequest::from_node() const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageRequest.from_node)
  return _internal_from_node();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ForwardMessageRequest::set_from_node(ArgT0&& arg0, ArgT... args) {
 
 _impl_.from_node_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageRequest.from_node)
}
inline std::string* ForwardMessageRequest::mutable_from_node() {
  std::string* _s = _internal_mutable_from_node();
  // @@protoc_insertion_point(field_mutable:gateway.ForwardMessageRequest.from_node)
  return _s;
}
inline const std::string& ForwardMessageRequest::_internal_from_node() const {
  return _impl_.from_node_.Get();
}
inline void ForwardMessageRequest::_internal_set_from_node(const std::string& value) {
  
  _impl_.from_node_.Set(value, GetArenaForAllocation());
}
inline std::string* ForwardMessageRequest::_internal_mutable_from_node() {
  
  return _impl_.from_node_.Mutable(GetArenaForAllocation());
}
inline std::string* ForwardMessageRequest::release_from_node() {
  // @@protoc_insertion_point(field_release:gateway.ForwardMessageRequest.from_node)
  return _impl_.from_node_.Release();
}
inline void ForwardMessageRequest::set_allocated_from_node(std::string* from_node) {
  if (from_node != nullptr) {
    
  } else {
    
  }
  _impl_.from_node_.SetAllocated(from_node, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.from_node_.IsDefault()) {
    _impl_.from_node_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gateway.ForwardMessageRequest.from_node)
}

// int64 timestamp = 4;
inline void ForwardMessageRequest::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t ForwardMessageRequest::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t ForwardMessageRequest::timestamp() const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageRequest.timestamp)
  return _internal_timestamp();
}
inline void ForwardMessageRequest::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void ForwardMessageRequest::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageRequest.timestamp)
}

// -------------------------------------------------------------------

// ForwardMessageResponse

// bool success = 1;
inline void ForwardMessageResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool ForwardMessageResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool ForwardMessageResponse::success() const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageResponse.success)
  return _internal_success();
}
inline void ForwardMessageResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void ForwardMessageResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageResponse.success)
}

// string error_message = 2;
inline void ForwardMessageResponse::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& ForwardMessageResponse::error_message() const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageResponse.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ForwardMessageResponse::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageResponse.error_message)
}
inline std::string* ForwardMessageResponse::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:gateway.ForwardMessageResponse.error_message)
  return _s;
}
inline const std::string& ForwardMessageResponse::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void ForwardMessageResponse::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* ForwardMessageResponse::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* ForwardMessageResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:gateway.ForwardMessageResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void ForwardMessageResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gateway.ForwardMessageResponse.error_message)
}

// bool user_online = 3;
inline void ForwardMessageResponse::clear_user_online() {
  _impl_.user_online_ = false;
}
inline bool ForwardMessageResponse::_internal_user_online() const {
  return _impl_.user_online_;
}
inline bool ForwardMessageResponse::user_online() const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageResponse.user_online)
  return _internal_user_online();
}
inline void ForwardMessageResponse::_internal_set_user_online(bool value) {
  
  _impl_.user_online_ = value;
}
inline void ForwardMessageResponse::set_user_online(bool value) {
  _internal_set_user_online(value);
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageResponse.user_online)
}

// -------------------------------------------------------------------

// ForwardMessageBatchRequest

// repeated .gateway.ForwardMessageRequest messages = 1;
inline int ForwardMessageBatchRequest::_internal_messages_size() const {
  return _impl_.messages_.size();
}
inline int ForwardMessageBatchRequest::messages_size() const {
  return _internal_messages_size();
}
inline void ForwardMessageBatchRequest::clear_messages() {
  _impl_.messages_.Clear();
}
inline ::gateway::ForwardMessageRequest* ForwardMessageBatchRequest::mutable_messages(int index) {
  // @@protoc_insertion_point(field_mutable:gateway.ForwardMessageBatchRequest.messages)
  return _impl_.messages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::ForwardMessageRequest >*
ForwardMessageBatchRequest::mutable_messages() {
  // @@protoc_insertion_point(field_mutable_list:gateway.ForwardMessageBatchRequest.messages)
  return &_impl_.messages_;
}
inline const ::gateway::ForwardMessageRequest& ForwardMessageBatchRequest::_internal_messages(int index) const {
  return _impl_.messages_.Get(index);
}
inline const ::gateway::ForwardMessageRequest& ForwardMessageBatchRequest::messages(int index) const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageBatchRequest.messages)
  return _internal_messages(index);
}
inline ::gateway::ForwardMessageRequest* ForwardMessageBatchRequest::_internal_add_messages() {
  return _impl_.messages_.Add();
}
inline ::gateway::ForwardMessageRequest* ForwardMessageBatchRequest::add_messages() {
  ::gateway::ForwardMessageRequest* _add = _internal_add_messages();
  // @@protoc_insertion_point(field_add:gateway.ForwardMessageBatchRequest.messages)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gateway::ForwardMessageRequest >&
ForwardMessageBatchRequest::messages() const {
  // @@protoc_insertion_point(field_list:gateway.ForwardMessageBatchRequest.messages)
  return _impl_.messages_;
}

// -------------------------------------------------------------------

// ForwardMessageBatchResponse

// int32 success_count = 1;
inline void ForwardMessageBatchResponse::clear_success_count() {
  _impl_.success_count_ = 0;
}
inline int32_t ForwardMessageBatchResponse::_internal_success_count() const {
  return _impl_.success_count_;
}
inline int32_t ForwardMessageBatchResponse::success_count() const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageBatchResponse.success_count)
  return _internal_success_count();
}
inline void ForwardMessageBatchResponse::_internal_set_success_count(int32_t value) {
  
  _impl_.success_count_ = value;
}
inline void ForwardMessageBatchResponse::set_success_count(int32_t value) {
  _internal_set_success_count(value);
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageBatchResponse.success_count)
}

// int32 failed_count = 2;
inline void ForwardMessageBatchResponse::clear_failed_count() {
  _impl_.failed_count_ = 0;
}
inline int32_t ForwardMessageBatchResponse::_internal_failed_count() const {
  return _impl_.failed_count_;
}
inline int32_t ForwardMessageBatchResponse::failed_count() const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageBatchResponse.failed_count)
  return _internal_failed_count();
}
inline void ForwardMessageBatchResponse::_internal_set_failed_count(int32_t value) {
  
  _impl_.failed_count_ = value;
}
inline void ForwardMessageBatchResponse::set_failed_count(int32_t value) {
  _internal_set_failed_count(value);
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageBatchResponse.failed_count)
}

// repeated string errors = 3;
inline int ForwardMessageBatchResponse::_internal_errors_size() const {
  return _impl_.errors_.size();
}
inline int ForwardMessageBatchResponse::errors_size() const {
  return _internal_errors_size();
}
inline void ForwardMessageBatchResponse::clear_errors() {
  _impl_.errors_.Clear();
}
inline std::string* ForwardMessageBatchResponse::add_errors() {
  std::string* _s = _internal_add_errors();
  // @@protoc_insertion_point(field_add_mutable:gateway.ForwardMessageBatchResponse.errors)
  return _s;
}
inline const std::string& ForwardMessageBatchResponse::_internal_errors(int index) const {
  return _impl_.errors_.Get(index);
}
inline const std::string& ForwardMessageBatchResponse::errors(int index) const {
  // @@protoc_insertion_point(field_get:gateway.ForwardMessageBatchResponse.errors)
  return _internal_errors(index);
}
inline std::string* ForwardMessageBatchResponse::mutable_errors(int index) {
  // @@protoc_insertion_point(field_mutable:gateway.ForwardMessageBatchResponse.errors)
  return _impl_.errors_.Mutable(index);
}
inline void ForwardMessageBatchResponse::set_errors(int index, const std::string& value) {
  _impl_.errors_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageBatchResponse.errors)
}
inline void ForwardMessageBatchResponse::set_errors(int index, std::string&& value) {
  _impl_.errors_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:gateway.ForwardMessageBatchResponse.errors)
}
inline void ForwardMessageBatchResponse::set_errors(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.errors_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:gateway.ForwardMessageBatchResponse.errors)
}
inline void ForwardMessageBatchResponse::set_errors(int index, const char* value, size_t size) {
  _impl_.errors_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gateway.ForwardMessageBatchResponse.errors)
}
inline std::string* ForwardMessageBatchResponse::_internal_add_errors() {
  return _impl_.errors_.Add();
}
inline void ForwardMessageBatchResponse::add_errors(const std::string& value) {
  _impl_.errors_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:gateway.ForwardMessageBatchResponse.errors)
}
inline void ForwardMessageBatchResponse::add_errors(std::string&& value) {
  _impl_.errors_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:gateway.ForwardMessageBatchResponse.errors)
}
inline void ForwardMessageBatchResponse::add_errors(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.errors_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:gateway.ForwardMessageBatchResponse.errors)
}
inline void ForwardMessageBatchResponse::add_errors(const char* value, size_t size) {
  _impl_.errors_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:gateway.ForwardMessageBatchResponse.errors)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ForwardMessageBatchResponse::errors() const {
  // @@protoc_insertion_point(field_list:gateway.ForwardMessageBatchResponse.errors)
  return _impl_.errors_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ForwardMessageBatchResponse::mutable_errors() {
  // @@protoc_insertion_point(field_mutable_list:gateway.ForwardMessageBatchResponse.errors)
  return &_impl_.errors_;
}

// -------------------------------------------------------------------

// HealthCheckRequest

// string node_id = 1;
inline void HealthCheckRequest::clear_node_id() {
  _impl_.node_id_.ClearToEmpty();
}
inline const std::string& HealthCheckRequest::node_id() const {
  // @@protoc_insertion_point(field_get:gateway.HealthCheckRequest.node_id)
  return _internal_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HealthCheckRequest::set_node_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gateway.HealthCheckRequest.node_id)
}
inline std::string* HealthCheckRequest::mutable_node_id() {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:gateway.HealthCheckRequest.node_id)
  return _s;
}
inline const std::string& HealthCheckRequest::_internal_node_id() const {
  return _impl_.node_id_.Get();
}
inline void HealthCheckRequest::_internal_set_node_id(const std::string& value) {
  
  _impl_.node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* HealthCheckRequest::_internal_mutable_node_id() {
  
  return _impl_.node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* HealthCheckRequest::release_node_id() {
  // @@protoc_insertion_point(field_release:gateway.HealthCheckRequest.node_id)
  return _impl_.node_id_.Release();
}
inline void HealthCheckRequest::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    
  } else {
    
  }
  _impl_.node_id_.SetAllocated(node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.node_id_.IsDefault()) {
    _impl_.node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gateway.HealthCheckRequest.node_id)
}

// -------------------------------------------------------------------

// HealthCheckResponse

// bool healthy = 1;
inline void HealthCheckResponse::clear_healthy() {
  _impl_.healthy_ = false;
}
inline bool HealthCheckResponse::_internal_healthy() const {
  return _impl_.healthy_;
}
inline bool HealthCheckResponse::healthy() const {
  // @@protoc_insertion_point(field_get:gateway.HealthCheckResponse.healthy)
  return _internal_healthy();
}
inline void HealthCheckResponse::_internal_set_healthy(bool value) {
  
  _impl_.healthy_ = value;
}
inline void HealthCheckResponse::set_healthy(bool value) {
  _internal_set_healthy(value);
  // @@protoc_insertion_point(field_set:gateway.HealthCheckResponse.healthy)
}

// int32 active_connections = 2;
inline void HealthCheckResponse::clear_active_connections() {
  _impl_.active_connections_ = 0;
}
inline int32_t HealthCheckResponse::_internal_active_connections() const {
  return _impl_.active_connections_;
}
inline int32_t HealthCheckResponse::active_connections() const {
  // @@protoc_insertion_point(field_get:gateway.HealthCheckResponse.active_connections)
  return _internal_active_connections();
}
inline void HealthCheckResponse::_internal_set_active_connections(int32_t value) {
  
  _impl_.active_connections_ = value;
}
inline void HealthCheckResponse::set_active_connections(int32_t value) {
  _internal_set_active_connections(value);
  // @@protoc_insertion_point(field_set:gateway.HealthCheckResponse.active_connections)
}

// int32 total_connections = 3;
inline void HealthCheckResponse::clear_total_connections() {
  _impl_.total_connections_ = 0;
}
inline int32_t HealthCheckResponse::_internal_total_connections() const {
  return _impl_.total_connections_;
}
inline int32_t HealthCheckResponse::total_connections() const {
  // @@protoc_insertion_point(field_get:gateway.HealthCheckResponse.total_connections)
  return _internal_total_connections();
}
inline void HealthCheckResponse::_internal_set_total_connections(int32_t value) {
  
  _impl_.total_connections_ = value;
}
inline void HealthCheckResponse::set_total_connections(int32_t value) {
  _internal_set_total_connections(value);
  // @@protoc_insertion_point(field_set:gateway.HealthCheckResponse.total_connections)
}

// double cpu_usage = 4;
inline void HealthCheckResponse::clear_cpu_usage() {
  _impl_.cpu_usage_ = 0;
}
inline double HealthCheckResponse::_internal_cpu_usage() const {
  return _impl_.cpu_usage_;
}
inline double HealthCheckResponse::cpu_usage() const {
  // @@protoc_insertion_point(field_get:gateway.HealthCheckResponse.cpu_usage)
  return _internal_cpu_usage();
}
inline void HealthCheckResponse::_internal_set_cpu_usage(double value) {
  
  _impl_.cpu_usage_ = value;
}
inline void HealthCheckResponse::set_cpu_usage(double value) {
  _internal_set_cpu_usage(value);
  // @@protoc_insertion_point(field_set:gateway.HealthCheckResponse.cpu_usage)
}

// double memory_usage = 5;
inline void HealthCheckResponse::clear_memory_usage() {
  _impl_.memory_usage_ = 0;
}
inline double HealthCheckResponse::_internal_memory_usage() const {
  return _impl_.memory_usage_;
}
inline double HealthCheckResponse::memory_usage() const {
  // @@protoc_insertion_point(field_get:gateway.HealthCheckResponse.memory_usage)
  return _internal_memory_usage();
}
inline void HealthCheckResponse::_internal_set_memory_usage(double value) {
  
  _impl_.memory_usage_ = value;
}
inline void HealthCheckResponse::set_memory_usage(double value) {
  _internal_set_memory_usage(value);
  // @@protoc_insertion_point(field_set:gateway.HealthCheckResponse.memory_usage)
}

// -------------------------------------------------------------------

// NodeStatsRequest

// string node_id = 1;
inline void NodeStatsRequest::clear_node_id() {
  _impl_.node_id_.ClearToEmpty();
}
inline const std::string& NodeStatsRequest::node_id() const {
  // @@protoc_insertion_point(field_get:gateway.NodeStatsRequest.node_id)
  return _internal_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void NodeStatsRequest::set_node_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gateway.NodeStatsRequest.node_id)
}
inline std::string* NodeStatsRequest::mutable_node_id() {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:gateway.NodeStatsRequest.node_id)
  return _s;
}
inline const std::string& NodeStatsRequest::_internal_node_id() const {
  return _impl_.node_id_.Get();
}
inline void NodeStatsRequest::_internal_set_node_id(const std::string& value) {
  
  _impl_.node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* NodeStatsRequest::_internal_mutable_node_id() {
  
  return _impl_.node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* NodeStatsRequest::release_node_id() {
  // @@protoc_insertion_point(field_release:gateway.NodeStatsRequest.node_id)
  return _impl_.node_id_.Release();
}
inline void NodeStatsRequest::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    
  } else {
    
  }
  _impl_.node_id_.SetAllocated(node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.node_id_.IsDefault()) {
    _impl_.node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gateway.NodeStatsRequest.node_id)
}

// -------------------------------------------------------------------

// NodeStatsResponse

// string node_id = 1;
inline void NodeStatsResponse::clear_node_id() {
  _impl_.node_id_.ClearToEmpty();
}
inline const std::string& NodeStatsResponse::node_id() const {
  // @@protoc_insertion_point(field_get:gateway.NodeStatsResponse.node_id)
  return _internal_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void NodeStatsResponse::set_node_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gateway.NodeStatsResponse.node_id)
}
inline std::string* NodeStatsResponse::mutable_node_id() {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:gateway.NodeStatsResponse.node_id)
  return _s;
}
inline const std::string& NodeStatsResponse::_internal_node_id() const {
  return _impl_.node_id_.Get();
}
inline void NodeStatsResponse::_internal_set_node_id(const std::string& value) {
  
  _impl_.node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* NodeStatsResponse::_internal_mutable_node_id() {
  
  return _impl_.node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* NodeStatsResponse::release_node_id() {
  // @@protoc_insertion_point(field_release:gateway.NodeStatsResponse.node_id)
  return _impl_.node_id_.Release();
}
inline void NodeStatsResponse::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    
  } else {
    
  }
  _impl_.node_id_.SetAllocated(node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.node_id_.IsDefault()) {
    _impl_.node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gateway.NodeStatsResponse.node_id)
}

// int32 active_connections = 2;
inline void NodeStatsResponse::clear_active_connections() {
  _impl_.active_connections_ = 0;
}
inline int32_t NodeStatsResponse::_internal_active_connections() const {
  return _impl_.active_connections_;
}
inline int32_t NodeStatsResponse::active_connections() const {
  // @@protoc_insertion_point(field_get:gateway.NodeStatsResponse.active_connections)
  return _internal_active_connections();
}
inline void NodeStatsResponse::_internal_set_active_connections(int32_t value) {
  
  _impl_.active_connections_ = value;
}
inline void NodeStatsResponse::set_active_connections(int32_t value) {
  _internal_set_active_connections(value);
  // @@protoc_insertion_point(field_set:gateway.NodeStatsResponse.active_connections)
}

// int32 total_connections = 3;
inline void NodeStatsResponse::clear_total_connections() {
  _impl_.total_connections_ = 0;
}
inline int32_t NodeStatsResponse::_internal_total_connections() const {
  return _impl_.total_connections_;
}
inline int32_t NodeStatsResponse::total_connections() const {
  // @@protoc_insertion_point(field_get:gateway.NodeStatsResponse.total_connections)
  return _internal_total_connections();
}
inline void NodeStatsResponse::_internal_set_total_connections(int32_t value) {
  
  _impl_.total_connections_ = value;
}
inline void NodeStatsResponse::set_total_connections(int32_t value) {
  _internal_set_total_connections(value);
  // @@protoc_insertion_point(field_set:gateway.NodeStatsResponse.total_connections)
}

// int64 messages_received = 4;
inline void NodeStatsResponse::clear_messages_received() {
  _impl_.messages_received_ = int64_t{0};
}
inline int64_t NodeStatsResponse::_internal_messages_received() const {
  return _impl_.messages_received_;
}
inline int64_t NodeStatsResponse::messages_received() const {
  // @@protoc_insertion_point(field_get:gateway.NodeStatsResponse.messages_received)
  return _internal_messages_received();
}
inline void NodeStatsResponse::_internal_set_messages_received(int64_t value) {
  
  _impl_.messages_received_ = value;
}
inline void NodeStatsResponse::set_messages_received(int64_t value) {
  _internal_set_messages_received(value);
  // @@protoc_insertion_point(field_set:gateway.NodeStatsResponse.messages_received)
}

// int64 messages_sent = 5;
inline void NodeStatsResponse::clear_messages_sent() {
  _impl_.messages_sent_ = int64_t{0};
}
inline int64_t NodeStatsResponse::_internal_messages_sent() const {
  return _impl_.messages_sent_;
}
inline int64_t NodeStatsResponse::messages_sent() const {
  // @@protoc_insertion_point(field_get:gateway.NodeStatsResponse.messages_sent)
  return _internal_messages_sent();
}
inline void NodeStatsResponse::_internal_set_messages_sent(int64_t value) {
  
  _impl_.messages_sent_ = value;
}
inline void NodeStatsResponse::set_messages_sent(int64_t value) {
  _internal_set_messages_sent(value);
  // @@protoc_insertion_point(field_set:gateway.NodeStatsResponse.messages_sent)
}

// int64 uptime_seconds = 6;
inline void NodeStatsResponse::clear_uptime_seconds() {
  _impl_.uptime_seconds_ = int64_t{0};
}
inline int64_t NodeStatsResponse::_internal_uptime_seconds() const {
  return _impl_.uptime_seconds_;
}
inline int64_t NodeStatsResponse::uptime_seconds() const {
  // @@protoc_insertion_point(field_get:gateway.NodeStatsResponse.uptime_seconds)
  return _internal_uptime_seconds();
}
inline void NodeStatsResponse::_internal_set_uptime_seconds(int64_t value) {
  
  _impl_.uptime_seconds_ = value;
}
inline void NodeStatsResponse::set_uptime_seconds(int64_t value) {
  _internal_set_uptime_seconds(value);
  // @@protoc_insertion_point(field_set:gateway.NodeStatsResponse.uptime_seconds)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace gateway

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fgateway_2eproto
