// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/gateway.proto
#ifndef GRPC_proto_2fgateway_2eproto__INCLUDED
#define GRPC_proto_2fgateway_2eproto__INCLUDED

#include "proto/gateway.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace gateway {

// 跨节点消息转发服务
class GatewayService final {
 public:
  static constexpr char const* service_full_name() {
    return "gateway.GatewayService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 转发消息到目标节点的用户
    virtual ::grpc::Status ForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::gateway::ForwardMessageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageResponse>> AsyncForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageResponse>>(AsyncForwardMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageResponse>> PrepareAsyncForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageResponse>>(PrepareAsyncForwardMessageRaw(context, request, cq));
    }
    // 批量转发消息
    virtual ::grpc::Status ForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::gateway::ForwardMessageBatchResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageBatchResponse>> AsyncForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageBatchResponse>>(AsyncForwardMessageBatchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageBatchResponse>> PrepareAsyncForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageBatchResponse>>(PrepareAsyncForwardMessageBatchRaw(context, request, cq));
    }
    // 节点健康检查
    virtual ::grpc::Status HealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::gateway::HealthCheckResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::HealthCheckResponse>> AsyncHealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::HealthCheckResponse>>(AsyncHealthCheckRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::HealthCheckResponse>> PrepareAsyncHealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::HealthCheckResponse>>(PrepareAsyncHealthCheckRaw(context, request, cq));
    }
    // 获取节点统计信息
    virtual ::grpc::Status GetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::gateway::NodeStatsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::NodeStatsResponse>> AsyncGetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::NodeStatsResponse>>(AsyncGetNodeStatsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::NodeStatsResponse>> PrepareAsyncGetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gateway::NodeStatsResponse>>(PrepareAsyncGetNodeStatsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 转发消息到目标节点的用户
      virtual void ForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest* request, ::gateway::ForwardMessageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest* request, ::gateway::ForwardMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 批量转发消息
      virtual void ForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest* request, ::gateway::ForwardMessageBatchResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest* request, ::gateway::ForwardMessageBatchResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 节点健康检查
      virtual void HealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest* request, ::gateway::HealthCheckResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void HealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest* request, ::gateway::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取节点统计信息
      virtual void GetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest* request, ::gateway::NodeStatsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest* request, ::gateway::NodeStatsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageResponse>* AsyncForwardMessageRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageResponse>* PrepareAsyncForwardMessageRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageBatchResponse>* AsyncForwardMessageBatchRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gateway::ForwardMessageBatchResponse>* PrepareAsyncForwardMessageBatchRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gateway::HealthCheckResponse>* AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gateway::HealthCheckResponse>* PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gateway::NodeStatsResponse>* AsyncGetNodeStatsRaw(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gateway::NodeStatsResponse>* PrepareAsyncGetNodeStatsRaw(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::gateway::ForwardMessageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageResponse>> AsyncForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageResponse>>(AsyncForwardMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageResponse>> PrepareAsyncForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageResponse>>(PrepareAsyncForwardMessageRaw(context, request, cq));
    }
    ::grpc::Status ForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::gateway::ForwardMessageBatchResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageBatchResponse>> AsyncForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageBatchResponse>>(AsyncForwardMessageBatchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageBatchResponse>> PrepareAsyncForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageBatchResponse>>(PrepareAsyncForwardMessageBatchRaw(context, request, cq));
    }
    ::grpc::Status HealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::gateway::HealthCheckResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::HealthCheckResponse>> AsyncHealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::HealthCheckResponse>>(AsyncHealthCheckRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::HealthCheckResponse>> PrepareAsyncHealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::HealthCheckResponse>>(PrepareAsyncHealthCheckRaw(context, request, cq));
    }
    ::grpc::Status GetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::gateway::NodeStatsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::NodeStatsResponse>> AsyncGetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::NodeStatsResponse>>(AsyncGetNodeStatsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::NodeStatsResponse>> PrepareAsyncGetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gateway::NodeStatsResponse>>(PrepareAsyncGetNodeStatsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest* request, ::gateway::ForwardMessageResponse* response, std::function<void(::grpc::Status)>) override;
      void ForwardMessage(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest* request, ::gateway::ForwardMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest* request, ::gateway::ForwardMessageBatchResponse* response, std::function<void(::grpc::Status)>) override;
      void ForwardMessageBatch(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest* request, ::gateway::ForwardMessageBatchResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void HealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest* request, ::gateway::HealthCheckResponse* response, std::function<void(::grpc::Status)>) override;
      void HealthCheck(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest* request, ::gateway::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest* request, ::gateway::NodeStatsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetNodeStats(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest* request, ::gateway::NodeStatsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageResponse>* AsyncForwardMessageRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageResponse>* PrepareAsyncForwardMessageRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageBatchResponse>* AsyncForwardMessageBatchRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gateway::ForwardMessageBatchResponse>* PrepareAsyncForwardMessageBatchRaw(::grpc::ClientContext* context, const ::gateway::ForwardMessageBatchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gateway::HealthCheckResponse>* AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gateway::HealthCheckResponse>* PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::gateway::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gateway::NodeStatsResponse>* AsyncGetNodeStatsRaw(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gateway::NodeStatsResponse>* PrepareAsyncGetNodeStatsRaw(::grpc::ClientContext* context, const ::gateway::NodeStatsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ForwardMessage_;
    const ::grpc::internal::RpcMethod rpcmethod_ForwardMessageBatch_;
    const ::grpc::internal::RpcMethod rpcmethod_HealthCheck_;
    const ::grpc::internal::RpcMethod rpcmethod_GetNodeStats_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 转发消息到目标节点的用户
    virtual ::grpc::Status ForwardMessage(::grpc::ServerContext* context, const ::gateway::ForwardMessageRequest* request, ::gateway::ForwardMessageResponse* response);
    // 批量转发消息
    virtual ::grpc::Status ForwardMessageBatch(::grpc::ServerContext* context, const ::gateway::ForwardMessageBatchRequest* request, ::gateway::ForwardMessageBatchResponse* response);
    // 节点健康检查
    virtual ::grpc::Status HealthCheck(::grpc::ServerContext* context, const ::gateway::HealthCheckRequest* request, ::gateway::HealthCheckResponse* response);
    // 获取节点统计信息
    virtual ::grpc::Status GetNodeStats(::grpc::ServerContext* context, const ::gateway::NodeStatsRequest* request, ::gateway::NodeStatsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ForwardMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ForwardMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ForwardMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessage(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageRequest* /*request*/, ::gateway::ForwardMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestForwardMessage(::grpc::ServerContext* context, ::gateway::ForwardMessageRequest* request, ::grpc::ServerAsyncResponseWriter< ::gateway::ForwardMessageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ForwardMessageBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ForwardMessageBatch() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ForwardMessageBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessageBatch(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageBatchRequest* /*request*/, ::gateway::ForwardMessageBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestForwardMessageBatch(::grpc::ServerContext* context, ::gateway::ForwardMessageBatchRequest* request, ::grpc::ServerAsyncResponseWriter< ::gateway::ForwardMessageBatchResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_HealthCheck() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::gateway::HealthCheckRequest* /*request*/, ::gateway::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealthCheck(::grpc::ServerContext* context, ::gateway::HealthCheckRequest* request, ::grpc::ServerAsyncResponseWriter< ::gateway::HealthCheckResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetNodeStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetNodeStats() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetNodeStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodeStats(::grpc::ServerContext* /*context*/, const ::gateway::NodeStatsRequest* /*request*/, ::gateway::NodeStatsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNodeStats(::grpc::ServerContext* context, ::gateway::NodeStatsRequest* request, ::grpc::ServerAsyncResponseWriter< ::gateway::NodeStatsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ForwardMessage<WithAsyncMethod_ForwardMessageBatch<WithAsyncMethod_HealthCheck<WithAsyncMethod_GetNodeStats<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ForwardMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ForwardMessage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::gateway::ForwardMessageRequest, ::gateway::ForwardMessageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::gateway::ForwardMessageRequest* request, ::gateway::ForwardMessageResponse* response) { return this->ForwardMessage(context, request, response); }));}
    void SetMessageAllocatorFor_ForwardMessage(
        ::grpc::MessageAllocator< ::gateway::ForwardMessageRequest, ::gateway::ForwardMessageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gateway::ForwardMessageRequest, ::gateway::ForwardMessageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ForwardMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessage(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageRequest* /*request*/, ::gateway::ForwardMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ForwardMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::gateway::ForwardMessageRequest* /*request*/, ::gateway::ForwardMessageResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ForwardMessageBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ForwardMessageBatch() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::gateway::ForwardMessageBatchRequest, ::gateway::ForwardMessageBatchResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::gateway::ForwardMessageBatchRequest* request, ::gateway::ForwardMessageBatchResponse* response) { return this->ForwardMessageBatch(context, request, response); }));}
    void SetMessageAllocatorFor_ForwardMessageBatch(
        ::grpc::MessageAllocator< ::gateway::ForwardMessageBatchRequest, ::gateway::ForwardMessageBatchResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gateway::ForwardMessageBatchRequest, ::gateway::ForwardMessageBatchResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ForwardMessageBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessageBatch(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageBatchRequest* /*request*/, ::gateway::ForwardMessageBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ForwardMessageBatch(
      ::grpc::CallbackServerContext* /*context*/, const ::gateway::ForwardMessageBatchRequest* /*request*/, ::gateway::ForwardMessageBatchResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_HealthCheck() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::gateway::HealthCheckRequest, ::gateway::HealthCheckResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::gateway::HealthCheckRequest* request, ::gateway::HealthCheckResponse* response) { return this->HealthCheck(context, request, response); }));}
    void SetMessageAllocatorFor_HealthCheck(
        ::grpc::MessageAllocator< ::gateway::HealthCheckRequest, ::gateway::HealthCheckResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gateway::HealthCheckRequest, ::gateway::HealthCheckResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::gateway::HealthCheckRequest* /*request*/, ::gateway::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HealthCheck(
      ::grpc::CallbackServerContext* /*context*/, const ::gateway::HealthCheckRequest* /*request*/, ::gateway::HealthCheckResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetNodeStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetNodeStats() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::gateway::NodeStatsRequest, ::gateway::NodeStatsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::gateway::NodeStatsRequest* request, ::gateway::NodeStatsResponse* response) { return this->GetNodeStats(context, request, response); }));}
    void SetMessageAllocatorFor_GetNodeStats(
        ::grpc::MessageAllocator< ::gateway::NodeStatsRequest, ::gateway::NodeStatsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gateway::NodeStatsRequest, ::gateway::NodeStatsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetNodeStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodeStats(::grpc::ServerContext* /*context*/, const ::gateway::NodeStatsRequest* /*request*/, ::gateway::NodeStatsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNodeStats(
      ::grpc::CallbackServerContext* /*context*/, const ::gateway::NodeStatsRequest* /*request*/, ::gateway::NodeStatsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ForwardMessage<WithCallbackMethod_ForwardMessageBatch<WithCallbackMethod_HealthCheck<WithCallbackMethod_GetNodeStats<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ForwardMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ForwardMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ForwardMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessage(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageRequest* /*request*/, ::gateway::ForwardMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ForwardMessageBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ForwardMessageBatch() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ForwardMessageBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessageBatch(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageBatchRequest* /*request*/, ::gateway::ForwardMessageBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_HealthCheck() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::gateway::HealthCheckRequest* /*request*/, ::gateway::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetNodeStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetNodeStats() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetNodeStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodeStats(::grpc::ServerContext* /*context*/, const ::gateway::NodeStatsRequest* /*request*/, ::gateway::NodeStatsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ForwardMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ForwardMessage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ForwardMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessage(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageRequest* /*request*/, ::gateway::ForwardMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestForwardMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ForwardMessageBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ForwardMessageBatch() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ForwardMessageBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessageBatch(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageBatchRequest* /*request*/, ::gateway::ForwardMessageBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestForwardMessageBatch(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_HealthCheck() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::gateway::HealthCheckRequest* /*request*/, ::gateway::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealthCheck(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetNodeStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetNodeStats() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetNodeStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodeStats(::grpc::ServerContext* /*context*/, const ::gateway::NodeStatsRequest* /*request*/, ::gateway::NodeStatsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNodeStats(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ForwardMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ForwardMessage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ForwardMessage(context, request, response); }));
    }
    ~WithRawCallbackMethod_ForwardMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessage(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageRequest* /*request*/, ::gateway::ForwardMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ForwardMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ForwardMessageBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ForwardMessageBatch() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ForwardMessageBatch(context, request, response); }));
    }
    ~WithRawCallbackMethod_ForwardMessageBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardMessageBatch(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageBatchRequest* /*request*/, ::gateway::ForwardMessageBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ForwardMessageBatch(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_HealthCheck() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->HealthCheck(context, request, response); }));
    }
    ~WithRawCallbackMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::gateway::HealthCheckRequest* /*request*/, ::gateway::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HealthCheck(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetNodeStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetNodeStats() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetNodeStats(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetNodeStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNodeStats(::grpc::ServerContext* /*context*/, const ::gateway::NodeStatsRequest* /*request*/, ::gateway::NodeStatsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNodeStats(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ForwardMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ForwardMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::gateway::ForwardMessageRequest, ::gateway::ForwardMessageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::gateway::ForwardMessageRequest, ::gateway::ForwardMessageResponse>* streamer) {
                       return this->StreamedForwardMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ForwardMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ForwardMessage(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageRequest* /*request*/, ::gateway::ForwardMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedForwardMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gateway::ForwardMessageRequest,::gateway::ForwardMessageResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ForwardMessageBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ForwardMessageBatch() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::gateway::ForwardMessageBatchRequest, ::gateway::ForwardMessageBatchResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::gateway::ForwardMessageBatchRequest, ::gateway::ForwardMessageBatchResponse>* streamer) {
                       return this->StreamedForwardMessageBatch(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ForwardMessageBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ForwardMessageBatch(::grpc::ServerContext* /*context*/, const ::gateway::ForwardMessageBatchRequest* /*request*/, ::gateway::ForwardMessageBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedForwardMessageBatch(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gateway::ForwardMessageBatchRequest,::gateway::ForwardMessageBatchResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_HealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_HealthCheck() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::gateway::HealthCheckRequest, ::gateway::HealthCheckResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::gateway::HealthCheckRequest, ::gateway::HealthCheckResponse>* streamer) {
                       return this->StreamedHealthCheck(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_HealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status HealthCheck(::grpc::ServerContext* /*context*/, const ::gateway::HealthCheckRequest* /*request*/, ::gateway::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHealthCheck(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gateway::HealthCheckRequest,::gateway::HealthCheckResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetNodeStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetNodeStats() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::gateway::NodeStatsRequest, ::gateway::NodeStatsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::gateway::NodeStatsRequest, ::gateway::NodeStatsResponse>* streamer) {
                       return this->StreamedGetNodeStats(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetNodeStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetNodeStats(::grpc::ServerContext* /*context*/, const ::gateway::NodeStatsRequest* /*request*/, ::gateway::NodeStatsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetNodeStats(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gateway::NodeStatsRequest,::gateway::NodeStatsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ForwardMessage<WithStreamedUnaryMethod_ForwardMessageBatch<WithStreamedUnaryMethod_HealthCheck<WithStreamedUnaryMethod_GetNodeStats<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ForwardMessage<WithStreamedUnaryMethod_ForwardMessageBatch<WithStreamedUnaryMethod_HealthCheck<WithStreamedUnaryMethod_GetNodeStats<Service > > > > StreamedService;
};

}  // namespace gateway


#endif  // GRPC_proto_2fgateway_2eproto__INCLUDED
